service:
  name: budgetbuddy-budgets
image:
  repository: budgetbuddy/budgets
secretName: budgetbuddy-budgets-secret
config:
  ASPNETCORE_ENVIRONMENT: Production
  OpenTelemetry__OtlpEndpoint: "http://otel-collector:4317"
  Seq__ServerUrl: "http://seq:5341"
