service:
  name: budgetbuddy-referencedata
image:
  repository: budgetbuddy/referencedata
secretName: budgetbuddy-referencedata-secret
config:
  ASPNETCORE_ENVIRONMENT: Production
  OpenTelemetry__OtlpEndpoint: "http://otel-collector:4317"
  Seq__ServerUrl: "http://seq:5341"
autoscaling:
  minReplicas: 1
  maxReplicas: 4
